Resolve "Set up read the docs for package"

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -92,3 +92,29 @@ package-build:
   when: manual
   tags:
     - rse-multi-builder
+
+docs-test:
+  stage: test
+  script:
+    - docker build -f dockerfiles/Dockerfile --target source -t image .
+    - docker run -u `id -u`:`id -g` image bash build_docs.sh
+  tags:
+    - rse-multi-builder
+
+docs-publish:
+  stage: package
+  rules:
+    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
+      when: always
+    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
+      when: never
+    - when: manual
+  script:
+    - |
+      if [ -z "$READTHEDOCS_WEBHOOK_SECRET" ] || [ -z "$READTHEDOCS_WEBHOOK_URL" ]; then
+        echo "Error: READTHEDOCS_WEBHOOK_SECRET and/or READTHEDOCS_WEBHOOK_URL is not set."
+        exit 1
+      fi
+    - curl -X POST -d "branches=latest" -d "token=${READTHEDOCS_WEBHOOK_SECRET}" -d "default_branch=${CI_COMMIT_BRANCH}" ${READTHEDOCS_WEBHOOK_URL}
+  tags:
+    - rse-multi-builder
